services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  jupyter:
    build:
      context: ./jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - ./arduino:/home/jovyan/.arduino15
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - ARDUINO_CLI_CONFIG=/home/jupyter/.arduino15/arduino-cli.yaml
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.notebook_dir=/home/jovyan/work"]

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
